### ISSUE TITLE
Infinite loop when installing via Poetry

### ISSUE THREAD

**Issue by maximiliancw** [bundesAPI/dip-bundestag-api#10]
Hi everyone,

using the [recommended Poetry command](https://github.com/bundesAPI/dip-bundestag-api/tree/main/python-client#poetry-install) does not work, since Poetry fails to resolve `botocore`'s dependencies, leading to an infinite resolver loop.

I managed to run a successful install by separately adding `botocore` as a dependency and then running the above mentioned command, as mentioned in [this comment](https://github.com/python-poetry/poetry/issues/37#issuecomment-378977500).

Since the docs might be auto-generated, you probably can't do much about that. Otherwise, it would be great to provide a short hint regarding this issue.

**Comment by wirthual** [comment]
I see similar behaviour on my end, thanks for reporting. 

Which python version/os are you using? 

I do not see the part where boto3 or botocore got introduced as dependencies so I think this is the first step to understand why poetry is not able to resolve the dependencies.

 I assume its connected to the fact we support down to 3.6 which might cause problems installing packages which dropped python3.6 support.

**Comment by maximiliancw** [comment]
Hi @wirthual!

Here is the (partial) output of  `poetry add -vvv deutschland -E dip_bundestag`:

```
PyPI: No release information found for botocore-1.4.45, skipping
PyPI: 1 packages found for botocore >=1.29.142,<1.30.0
   1: fact: botocore (1.29.142) depends on jmespath (>=0.7.1,<2.0.0)
   1: fact: botocore (1.29.142) depends on python-dateutil (>=2.1,<3.0.0)
   1: fact: botocore (1.29.142) depends on urllib3 (>=1.25.4,<1.27)
   1: derived: not botocore (==1.29.142)
   1: fact: no versions of botocore match >1.29.142,<1.30.0
   1: conflict: no versions of botocore match >1.29.142,<1.30.0
   1: !  botocore (>1.29.142,<1.30.0) is partially satisfied by not  botocore (1.29.142)
   1: ! which is caused by "botocore (1.29.142) depends on urllib3 (>=1.25.4,<1.27)"
   1: ! thus: botocore (>=1.29.142,<1.30.0) requires urllib3 (>=1.25.4,<1.27)
   1: fact: botocore (>=1.29.142,<1.30.0) requires urllib3 (>=1.25.4,<1.27)
   1: derived: not botocore (>=1.29.142,<1.30.0)
   1: derived: not boto3 (==1.26.142)
```

I can't really tell where the dependency is coming from though. I'm running Python 3.10.2 on macOS 12.6.3 — let me know if that helps

**Comment by wirthual** [comment]
Hi @maximiliancw ,

We just released a new version of the deutschland package (0.3.2) without the boto3 dependency. This should fix this problem. 

If you could test if you still run into this problem, that would be super helpful.

**Comment by maximiliancw** [comment]
Hi @wirthual, everything now works as expected here. Thanks for the update!
